(function(){
'use strict';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let type='url', current={id:null,name:null,type:null,payload:null,trackingUrl:null,svg:null};
const fields=$('#fields'), qrName=$('#qrName'), nameStatus=$('#nameStatus'), formError=$('#formError'), createBtn=$('#createBtn');
const templates={
 url:`<label class="field-label">Website URL<input id="urlInput" type="url" placeholder="https://ramanicars.com/"><small>A missing protocol is automatically converted to https://.</small></label>`,
 text:`<label class="field-label">Text<textarea id="textInput" rows="5" placeholder="Enter text"></textarea></label>`,
 email:`<label class="field-label">Email address<input id="emailInput" type="email" placeholder="name@ramani.com"></label><label class="field-label">Subject<input id="emailSubject" type="text" placeholder="Subject"></label><label class="field-label">Message<textarea id="emailMessage" rows="4" placeholder="Message"></textarea></label>`,
 phone:`<label class="field-label">Phone number<input id="phoneInput" type="tel" placeholder="+91 98765 43210"></label>`,
 sms:`<label class="field-label">Phone number<input id="smsPhone" type="tel" placeholder="+91 98765 43210"></label><label class="field-label">Message<textarea id="smsMessage" rows="4" placeholder="SMS message"></textarea></label>`,
 wifi:`<label class="field-label">Network name / SSID<input id="wifiSsid" type="text" placeholder="Wi‑Fi name"></label><label class="field-label">Password<input id="wifiPassword" type="text" placeholder="Wi‑Fi password"></label><label class="field-label">Security<select id="wifiSecurity"><option value="WPA">WPA/WPA2</option><option value="WEP">WEP</option><option value="nopass">None</option></select></label><label class="check-label"><input id="wifiHidden" type="checkbox"> Hidden network</label>`
};
function renderFields(){fields.innerHTML=templates[type]; clearCreated();}
function esc(v){return String(v).replace(/([\\;,:])/g,'\\$1');}
function payload(){
 if(type==='url'){let v=$('#urlInput').value.trim(); if(!v)throw Error('Website URL is required.'); if(!/^https?:\/\//i.test(v))v='https://'+v; try{new URL(v);}catch{throw Error('Enter a valid website URL.');} return v;}
 if(type==='text'){const v=$('#textInput').value.trim(); if(!v)throw Error('Text is required.'); return v;}
 if(type==='email'){const e=$('#emailInput').value.trim(),s=$('#emailSubject').value.trim(),m=$('#emailMessage').value.trim(); if(!/^\S+@\S+\.\S+$/.test(e))throw Error('Enter a valid email address.'); return `mailto:${e}?subject=${encodeURIComponent(s)}&body=${encodeURIComponent(m)}`;}
 if(type==='phone'){const v=$('#phoneInput').value.trim(); if(!/[0-9]{5,}/.test(v.replace(/\D/g,'')))throw Error('Enter a valid phone number.'); return 'tel:'+v.replace(/\s+/g,'');}
 if(type==='sms'){const p=$('#smsPhone').value.trim(),m=$('#smsMessage').value.trim(); if(!/[0-9]{5,}/.test(p.replace(/\D/g,'')))throw Error('Enter a valid phone number.'); return `sms:${p.replace(/\s+/g,'')}?body=${encodeURIComponent(m)}`;}
 const ssid=$('#wifiSsid').value.trim(), pass=$('#wifiPassword').value, sec=$('#wifiSecurity').value, hidden=$('#wifiHidden').checked; if(!ssid)throw Error('Wi‑Fi network name is required.'); return `WIFI:T:${sec};S:${esc(ssid)};P:${esc(pass)};H:${hidden?'true':'false'};;`;
}
function clearCreated(){current={id:null,name:null,type:null,payload:null,trackingUrl:null,svg:null}; $('#qrFrame').innerHTML='<div class="qr-placeholder">Complete the fields and create the tracked QR.</div>'; $('#previewStatus').textContent='Waiting'; $('#createdInfo').hidden=true; $('#pngBtn').disabled=true; $('#svgBtn').disabled=true;}
let nameTimer; qrName.addEventListener('input',()=>{clearTimeout(nameTimer); clearCreated(); const n=qrName.value.trim(); if(!n){nameStatus.textContent='Enter a unique QR Name.'; nameStatus.className='status-text';return;} nameStatus.textContent='Checking name…'; nameStatus.className='status-text'; nameTimer=setTimeout(async()=>{try{const r=await RamaniQrApi.checkName(n); nameStatus.textContent=r.available?'Name is available.':'This QR Name already exists.'; nameStatus.className='status-text '+(r.available?'ok':'bad');}catch(e){nameStatus.textContent=e.message; nameStatus.className='status-text bad';}},450);});
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.type;renderFields();}));
$('#margin').addEventListener('input',e=>$('#marginValue').textContent=e.target.value+' modules');
function makeSvg(data){const q=qrcode(0,$('#errorLevel').value);q.addData(data);q.make();const size=Number($('#qrSize').value),margin=Number($('#margin').value),count=q.getModuleCount(),cell=Math.max(1,Math.floor((size-margin*2)/count)),actual=cell*count+margin*2,fg=$('#fgColor').value,bg=$('#bgColor').value;let s=`<svg xmlns="http://www.w3.org/2000/svg" width="${actual}" height="${actual}" viewBox="0 0 ${actual} ${actual}"><rect width="100%" height="100%" fill="${bg}"/>`;for(let r=0;r<count;r++)for(let c=0;c<count;c++)if(q.isDark(r,c))s+=`<rect x="${margin+c*cell}" y="${margin+r*cell}" width="${cell}" height="${cell}" fill="${fg}"/>`;return s+'</svg>';}
createBtn.addEventListener('click',async()=>{formError.hidden=true;const name=qrName.value.trim();if(!name){showErr('QR Name is required.');return;} createBtn.disabled=true;createBtn.textContent='Creating…';try{const check=await RamaniQrApi.checkName(name);if(!check.available)throw Error('QR Name already exists. Please use a unique name.'); const p=payload(); const reg=await RamaniQrApi.register({qrName:name,qrType:type,payload:p}); const base=new URL('go.html',location.href);base.searchParams.set('id',reg.qrId); current={id:reg.qrId,name,type,payload:p,trackingUrl:base.toString(),svg:null}; current.svg=makeSvg(current.trackingUrl); $('#qrFrame').innerHTML=current.svg; $('#previewStatus').textContent='Tracked'; $('#createdInfo').hidden=false; $('#createdInfo').innerHTML=`<strong>${name}</strong><span>${type.toUpperCase()} · ID ${reg.qrId}</span>`; $('#pngBtn').disabled=false;$('#svgBtn').disabled=false; nameStatus.textContent='Registered successfully. This name is now reserved.';nameStatus.className='status-text ok';}catch(e){showErr(e.message);}finally{createBtn.disabled=false;createBtn.textContent='Create tracked QR';}});
function showErr(m){formError.hidden=false;formError.textContent=m;}
$('#svgBtn').addEventListener('click',()=>{if(!current.svg)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([current.svg],{type:'image/svg+xml'}));a.download=safeName()+'.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
$('#pngBtn').addEventListener('click',()=>{if(!current.svg)return;const img=new Image(),blob=new Blob([current.svg],{type:'image/svg+xml'}),u=URL.createObjectURL(blob);img.onload=()=>{const size=Number($('#qrSize').value),c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle=$('#bgColor').value;x.fillRect(0,0,size,size);x.drawImage(img,0,0,size,size);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=safeName()+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});URL.revokeObjectURL(u);};img.src=u;});
function safeName(){return (current.name||'ramani-qr').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
$('#resetBtn').addEventListener('click',()=>{qrName.value='';type='url';$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.type==='url'));renderFields();nameStatus.textContent='Enter a unique QR Name.';nameStatus.className='status-text';formError.hidden=true;});
renderFields();
})();
